jobs:
- job: macos
  pool:
    vmImage: 'macos-10.14'
  variables:
    TARGET: x86_64-apple-darwin
  steps:
  - script: |
      brew install autoconf automake libtool pkg-config
    displayName: Install autotools
  - script: |
      brew install libplist
    displayName: Install libplist
  - script: |
      ./autogen.sh --host=$TARGET --without-cython --enable-static=no --enable-shared=yes
      make
    displayName: Build
  - script: |
      make check
    displayName: test

- job: linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    TARGET: x86_64-unknown-linux-gnu
    CFLAGS: -fPIC
  container:
    image: ubuntu:18.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y --no-install-recommends lsb-release automake make libtool clang gnupg pkg-config
    displayName: Install build dependencies
  - script: |
      echo "deb http://ppa.launchpad.net/quamotion/ppa/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list.d/quamotion.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E25E7A74
      sudo apt-get update
      sudo apt-get install -y libplist-dev
    displayName: Install libplist
  - script: |
      ./autogen.sh --host=$TARGET --without-cython --enable-static=no --enable-shared=yes
      make
    displayName: Build
  - script: |
      make check
    displayName: test